version: '3.8'

services:
  cxo_prism_app:
    build: .
    ports:
      - "8502:8502"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json
      - BUCKET_NAME=cxo-prism
      - PROJECT_ID=deft-clarity-461011-c7
      - REGION=us-central1
      - DB_USER=report_user
      - DB_PASS=test123
      - DB_HOST=35.244.42.223
      - DB_NAME=cxo_prism
    volumes:
      - .:/app
      - ./service_account.json:/app/service_account.json
    command: streamlit run streamlit_app.py --server.port=8502 --server.enableCORS=false
